version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      docker: 24
    commands:
      - pip install -r requirements.txt pytest

  pre_build:
    commands:
      # Run unit tests with DynamoDB Local
      - docker run -d --name dynamodb-test -p 8000:8000 amazon/dynamodb-local -jar DynamoDBLocal.jar -sharedDb -inMemory
      - sleep 3
      - >
        AWS_REGION=us-east-1
        AWS_ACCESS_KEY_ID=testing
        AWS_SECRET_ACCESS_KEY=testing
        DYNAMODB_ENDPOINT=http://localhost:8000
        ADMIN_INVITE_CODE=TESTCODE
        python -m pytest tests/ -v
      # ECR login
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:
      - docker build -t $ECR_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $ECR_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REPO_URI:latest

  post_build:
    commands:
      - docker push $ECR_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_REPO_URI:latest
